server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    username: root
    password: "H5051215qaz_"
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: userservice
mybatis:
  type-aliases-package: com.huike.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.huike: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/